"""initial schema with 9 core tables and constraints

Revision ID: 56438c936570
Revises: 
Create Date: 2025-11-03 15:36:38.735052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '56438c936570'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_name'), 'data_source', ['name'], unique=True)
    op.create_table('instrument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_cap', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_sector'), 'instrument', ['sector'], unique=False)
    op.create_index(op.f('ix_instrument_symbol'), 'instrument', ['symbol'], unique=True)
    op.create_table('analyst_estimate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('target_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'as_of_date', 'target_period', name='uq_analyst_estimate_instrument_period')
    )
    op.create_index(op.f('ix_analyst_estimate_as_of_date'), 'analyst_estimate', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_analyst_estimate_instrument_id'), 'analyst_estimate', ['instrument_id'], unique=False)
    op.create_table('company_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ownership', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('management', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_fundamentals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitive_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks_catalysts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'snapshot_date', name='uq_company_snapshot_instrument_date')
    )
    op.create_index('ix_company_snapshot_instrument_date_desc', 'company_snapshot', ['instrument_id', 'snapshot_date'], unique=False, postgresql_ops={'snapshot_date': 'DESC'})
    op.create_index(op.f('ix_company_snapshot_instrument_id'), 'company_snapshot', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_company_snapshot_snapshot_date'), 'company_snapshot', ['snapshot_date'], unique=False)
    op.create_table('earnings_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('fiscal_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_event_instrument_id'), 'earnings_event', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_earnings_event_report_date'), 'earnings_event', ['report_date'], unique=False)
    op.create_index(op.f('ix_earnings_event_scheduled_for'), 'earnings_event', ['scheduled_for'], unique=False)
    op.create_table('financial_statement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('income_statement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cash_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'period_end', 'period_type', name='uq_financial_instrument_period')
    )
    op.create_index('ix_financial_instrument_period_desc', 'financial_statement', ['instrument_id', 'period_end'], unique=False, postgresql_ops={'period_end': 'DESC'})
    op.create_index(op.f('ix_financial_statement_instrument_id'), 'financial_statement', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_financial_statement_period_end'), 'financial_statement', ['period_end'], unique=False)
    op.create_table('macro_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'snapshot_date', name='uq_macro_snapshot_region_date')
    )
    op.create_index(op.f('ix_macro_snapshot_region'), 'macro_snapshot', ['region'], unique=False)
    op.create_index(op.f('ix_macro_snapshot_snapshot_date'), 'macro_snapshot', ['snapshot_date'], unique=False)
    op.create_table('ohlcv_bar_pg',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instrument_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('high >= low', name='check_ohlcv_high_low'),
    sa.CheckConstraint('high >= open AND high >= close', name='check_ohlcv_high_bounds'),
    sa.CheckConstraint('low <= open AND low <= close', name='check_ohlcv_low_bounds'),
    sa.CheckConstraint('volume >= 0', name='check_volume_positive'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ts', 'data_source_id', name='uq_ohlcv_instrument_ts_source')
    )
    op.create_index(op.f('ix_ohlcv_bar_pg_instrument_id'), 'ohlcv_bar_pg', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_bar_pg_ts'), 'ohlcv_bar_pg', ['ts'], unique=False)
    op.create_index('ix_ohlcv_instrument_ts_desc', 'ohlcv_bar_pg', ['instrument_id', 'ts'], unique=False, postgresql_ops={'ts': 'DESC'})
    op.create_table('sector_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector', 'snapshot_date', name='uq_sector_snapshot_date')
    )
    op.create_index(op.f('ix_sector_snapshot_sector'), 'sector_snapshot', ['sector'], unique=False)
    op.create_index(op.f('ix_sector_snapshot_snapshot_date'), 'sector_snapshot', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sector_snapshot_snapshot_date'), table_name='sector_snapshot')
    op.drop_index(op.f('ix_sector_snapshot_sector'), table_name='sector_snapshot')
    op.drop_table('sector_snapshot')
    op.drop_index('ix_ohlcv_instrument_ts_desc', table_name='ohlcv_bar_pg', postgresql_ops={'ts': 'DESC'})
    op.drop_index(op.f('ix_ohlcv_bar_pg_ts'), table_name='ohlcv_bar_pg')
    op.drop_index(op.f('ix_ohlcv_bar_pg_instrument_id'), table_name='ohlcv_bar_pg')
    op.drop_table('ohlcv_bar_pg')
    op.drop_index(op.f('ix_macro_snapshot_snapshot_date'), table_name='macro_snapshot')
    op.drop_index(op.f('ix_macro_snapshot_region'), table_name='macro_snapshot')
    op.drop_table('macro_snapshot')
    op.drop_index(op.f('ix_financial_statement_period_end'), table_name='financial_statement')
    op.drop_index(op.f('ix_financial_statement_instrument_id'), table_name='financial_statement')
    op.drop_index('ix_financial_instrument_period_desc', table_name='financial_statement', postgresql_ops={'period_end': 'DESC'})
    op.drop_table('financial_statement')
    op.drop_index(op.f('ix_earnings_event_scheduled_for'), table_name='earnings_event')
    op.drop_index(op.f('ix_earnings_event_report_date'), table_name='earnings_event')
    op.drop_index(op.f('ix_earnings_event_instrument_id'), table_name='earnings_event')
    op.drop_table('earnings_event')
    op.drop_index(op.f('ix_company_snapshot_snapshot_date'), table_name='company_snapshot')
    op.drop_index(op.f('ix_company_snapshot_instrument_id'), table_name='company_snapshot')
    op.drop_index('ix_company_snapshot_instrument_date_desc', table_name='company_snapshot', postgresql_ops={'snapshot_date': 'DESC'})
    op.drop_table('company_snapshot')
    op.drop_index(op.f('ix_analyst_estimate_instrument_id'), table_name='analyst_estimate')
    op.drop_index(op.f('ix_analyst_estimate_as_of_date'), table_name='analyst_estimate')
    op.drop_table('analyst_estimate')
    op.drop_index(op.f('ix_instrument_symbol'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_sector'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_data_source_name'), table_name='data_source')
    op.drop_table('data_source')
    # ### end Alembic commands ###
